// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by tool/gen_strings.dart from:
//   strings/strings_fr.json
//   strings/strings_en_welcome.json
// Edit those files, then run `dart run tool/gen_strings.dart`.

/// The app's French text, from `strings/strings_fr.json`.
abstract final class Strings {
  /// BAH Français
  static const commonAppName = 'BAH Français';

  /// Annuler
  static const commonCancel = 'Annuler';

  /// Enregistrer
  static const commonSave = 'Enregistrer';

  /// Supprimer
  static const commonDelete = 'Supprimer';

  /// Modifier
  static const commonEdit = 'Modifier';

  /// Fermer
  static const commonClose = 'Fermer';

  /// Retour
  static const commonBack = 'Retour';

  /// Rechercher
  static const commonSearch = 'Rechercher';

  /// Réessayer
  static const commonRetry = 'Réessayer';

  /// Annuler
  static const commonUndo = 'Annuler';

  /// Oui
  static const commonYes = 'Oui';

  /// Non
  static const commonNo = 'Non';

  /// Chargement…
  static const commonLoading = 'Chargement…';

  /// Illimité
  static const commonUnlimited = 'Illimité';

  /// Aucun
  static const commonNone = 'Aucun';

  /// {n} min
  static String commonMinutes({required int n}) => '$n min';

  /// {n} s
  static String commonSeconds({required int n}) => '$n s';

  /// Accueil
  static const navigationHome = 'Accueil';

  /// Mots
  static const navigationWords = 'Mots';

  /// Verbes
  static const navigationVerbs = 'Verbes';

  /// Statistiques
  static const navigationStats = 'Statistiques';

  /// Réglages
  static const navigationSettings = 'Réglages';

  /// Commencer
  static const homeStart = 'Commencer';

  /// Genre
  static const homeDrillGender = 'Genre';

  /// Vocabulaire
  static const homeDrillVocabulary = 'Vocabulaire';

  /// Conjugaison
  static const homeDrillConjugation = 'Conjugaison';

  /// {n} à réviser
  static String homeDueCount({required int n}) => '$n à réviser';

  /// Tout est à jour
  static const homeDueNone = 'Tout est à jour';

  /// Liste de révision
  static const homeReviewList = 'Liste de révision';

  /// Réglages de l’exercice
  static const homeDrillSettings = 'Réglages de l’exercice';

  /// Aucune catégorie choisie
  static const homeNoCategories = 'Aucune catégorie choisie';

  /// Préparation du contenu…
  static const homePreparingContent = 'Préparation du contenu…';

  /// {n} cartes
  static String drillCardsAnswered({required int n}) => '$n cartes';

  /// masculin
  static const drillGenderMasculine = 'masculin';

  /// féminin
  static const drillGenderFeminine = 'féminin';

  /// les deux
  static const drillGenderBoth = 'les deux';

  /// Votre réponse
  static const drillAnswerHint = 'Votre réponse';

  /// Votre réponse, avec l’article
  static const drillAnswerHintWithArticle = 'Votre réponse, avec l’article';

  /// Infinitif
  static const drillInfinitive = 'Infinitif';

  /// Temps
  static const drillTense = 'Temps';

  /// Je le connais
  static const drillIKnowIt = 'Je le connais';

  /// Je ne sais pas
  static const drillIDontKnow = 'Je ne sais pas';

  /// Suivant
  static const drillNext = 'Suivant';

  /// Correct
  static const drillResultCorrect = 'Correct';

  /// Presque
  static const drillResultAlmost = 'Presque';

  /// Incorrect
  static const drillResultIncorrect = 'Incorrect';

  /// Réponse : {answer}
  static String drillCorrectAnswer({required String answer}) =>
      'Réponse : $answer';

  /// Faute de frappe
  static const drillTypo = 'Faute de frappe';

  /// Trop facile
  static const drillTooEasy = 'Trop facile';

  /// Astuce
  static const drillTip = 'Astuce';

  /// Tout est à jour !
  static const drillAllCaughtUp = 'Tout est à jour !';

  /// Vous pouvez continuer avec les cartes les plus fragiles.
  static const drillFreePractice =
      'Vous pouvez continuer avec les cartes les plus fragiles.';

  /// Aucune carte disponible
  static const drillNoCards = 'Aucune carte disponible';

  /// Ouvrir les réglages
  static const drillOpenSettings = 'Ouvrir les réglages';

  /// Marqué comme connu
  static const drillMarkedKnown = 'Marqué comme connu';

  /// Terminer la session ?
  static const drillLeaveSession = 'Terminer la session ?';

  /// Résumé de session
  static const sessionSummaryTitle = 'Résumé de session';

  /// Cartes répondues
  static const sessionSummaryCardsAnswered = 'Cartes répondues';

  /// Réponses correctes
  static const sessionSummaryAccuracy = 'Réponses correctes';

  /// Durée
  static const sessionSummaryDuration = 'Durée';

  /// Terminer
  static const sessionSummaryFinish = 'Terminer';

  /// Continuer
  static const sessionSummaryResume = 'Continuer';

  /// Liste de révision
  static const reviewListTitle = 'Liste de révision';

  /// À réviser aujourd’hui
  static const reviewListDueToday = 'À réviser aujourd’hui';

  /// À risque
  static const reviewListAtRisk = 'À risque';

  /// Mots difficiles
  static const reviewListHardWords = 'Mots difficiles';

  /// Rien ici pour l’instant
  static const reviewListEmptyGroup = 'Rien ici pour l’instant';

  /// {n} cartes
  static String reviewListCardCount({required int n}) => '$n cartes';

  /// Mots
  static const wordsTitle = 'Mots';

  /// Ajouter un mot
  static const wordsAdd = 'Ajouter un mot';

  /// Rechercher un mot
  static const wordsSearchHint = 'Rechercher un mot';

  /// Catégorie
  static const wordsFilterCategory = 'Catégorie';

  /// Niveau
  static const wordsFilterLevel = 'Niveau';

  /// Source
  static const wordsFilterSource = 'Source';

  /// Mots difficiles uniquement
  static const wordsFilterHardOnly = 'Mots difficiles uniquement';

  /// Officiel
  static const wordsSourceOfficial = 'Officiel';

  /// Perso
  static const wordsSourcePersonal = 'Perso';

  /// A → Z
  static const wordsSortAlphabetical = 'A → Z';

  /// Les plus fragiles d’abord
  static const wordsSortWeakestFirst = 'Les plus fragiles d’abord';

  /// Aucun mot ne correspond.
  static const wordsEmpty = 'Aucun mot ne correspond.';

  /// Définition
  static const wordDetailDefinition = 'Définition';

  /// Synonymes
  static const wordDetailSynonyms = 'Synonymes';

  /// Phrases d’exemple
  static const wordDetailExamples = 'Phrases d’exemple';

  /// Catégorie
  static const wordDetailCategory = 'Catégorie';

  /// Niveau
  static const wordDetailLevel = 'Niveau';

  /// Vos cartes
  static const wordDetailYourCards = 'Vos cartes';

  /// Prochaine révision
  static const wordDetailNextReview = 'Prochaine révision';

  /// Révisions
  static const wordDetailReviewCount = 'Révisions';

  /// Oublis
  static const wordDetailLapseCount = 'Oublis';

  /// Je le connais
  static const wordDetailMarkKnown = 'Je le connais';

  /// Remettre en révision
  static const wordDetailBackToReview = 'Remettre en révision';

  /// Ajouter une image
  static const wordDetailAddImage = 'Ajouter une image';

  /// Retirer l’image
  static const wordDetailRemoveImage = 'Retirer l’image';

  /// Supprimer ce mot et ses cartes ?
  static const wordDetailDeleteConfirm = 'Supprimer ce mot et ses cartes ?';

  /// Ce mot fait partie de la liste officielle et ne peut pas être modifié.
  static const wordDetailOfficialWordNotice =
      'Ce mot fait partie de la liste officielle et ne peut pas être modifié.';

  /// Ajouter un mot
  static const addWordTitle = 'Ajouter un mot';

  /// Mot
  static const addWordWord = 'Mot';

  /// Genre
  static const addWordGender = 'Genre';

  /// Image
  static const addWordImage = 'Image';

  /// Choisir une image
  static const addWordChooseImage = 'Choisir une image';

  /// Définition
  static const addWordDefinition = 'Définition';

  /// Utilisée comme question quand il n’y a pas d’image.
  static const addWordDefinitionHelp =
      'Utilisée comme question quand il n’y a pas d’image.';

  /// Phrase d’exemple
  static const addWordExample = 'Phrase d’exemple';

  /// Synonymes
  static const addWordSynonyms = 'Synonymes';

  /// Séparez les synonymes par des virgules.
  static const addWordSynonymsHelp = 'Séparez les synonymes par des virgules.';

  /// Catégorie
  static const addWordCategory = 'Catégorie';

  /// Perso
  static const addWordCategoryPersonal = 'Perso';

  /// Ce mot existe déjà.
  static const addWordDuplicate = 'Ce mot existe déjà.';

  /// Voir la fiche
  static const addWordSeeExisting = 'Voir la fiche';

  /// Ce champ est obligatoire.
  static const addWordRequired = 'Ce champ est obligatoire.';

  /// Image trop lourde, elle a été réduite.
  static const addWordImageTooLarge = 'Image trop lourde, elle a été réduite.';

  /// Image illisible. Choisissez un autre fichier.
  static const addWordImageInvalid =
      'Image illisible. Choisissez un autre fichier.';

  /// Mot ajouté
  static const addWordSaved = 'Mot ajouté';

  /// Verbes
  static const verbsTitle = 'Verbes';

  /// Rechercher un verbe
  static const verbsSearchHint = 'Rechercher un verbe';

  /// Groupe
  static const verbsGroup = 'Groupe';

  /// Auxiliaire
  static const verbsAuxiliary = 'Auxiliaire';

  /// verbes en -er
  static const verbsGroupEr = 'verbes en -er';

  /// verbes en -ir
  static const verbsGroupIr = 'verbes en -ir';

  /// verbes en -re
  static const verbsGroupRe = 'verbes en -re';

  /// verbes irréguliers
  static const verbsGroupIrregular = 'verbes irréguliers';

  /// Aucun verbe ne correspond.
  static const verbsEmpty = 'Aucun verbe ne correspond.';

  /// Les nouveaux verbes arrivent avec les mises à jour du contenu.
  static const verbsNewVerbsNotice =
      'Les nouveaux verbes arrivent avec les mises à jour du contenu.';

  /// Conjugaison
  static const verbDetailConjugation = 'Conjugaison';

  /// Phrases
  static const verbDetailSentences = 'Phrases';

  /// Ajouter une phrase
  static const verbDetailAddSentence = 'Ajouter une phrase';

  /// Écrivez une phrase avec ___ à la place du verbe.
  static const verbDetailSentenceHelp =
      'Écrivez une phrase avec ___ à la place du verbe.';

  /// Personne
  static const verbDetailPerson = 'Personne';

  /// Réponse attendue
  static const verbDetailExpectedAnswer = 'Réponse attendue';

  /// Corrigez l’accord si nécessaire.
  static const verbDetailExpectedAnswerHelp =
      'Corrigez l’accord si nécessaire.';

  /// Phrase ajoutée
  static const verbDetailSentenceSaved = 'Phrase ajoutée';

  /// La phrase doit contenir ___ une seule fois.
  static const verbDetailMissingBlank =
      'La phrase doit contenir ___ une seule fois.';

  /// présent
  static const tensesPresent = 'présent';

  /// passé composé
  static const tensesPasseCompose = 'passé composé';

  /// imparfait
  static const tensesImparfait = 'imparfait';

  /// futur simple
  static const tensesFuturSimple = 'futur simple';

  /// je
  static const personsFirstSingular = 'je';

  /// tu
  static const personsSecondSingular = 'tu';

  /// il / elle
  static const personsThirdSingular = 'il / elle';

  /// nous
  static const personsFirstPlural = 'nous';

  /// vous
  static const personsSecondPlural = 'vous';

  /// ils / elles
  static const personsThirdPlural = 'ils / elles';

  /// débutant
  static const levelsBeginner = 'débutant';

  /// intermédiaire
  static const levelsIntermediate = 'intermédiaire';

  /// avancé
  static const levelsAdvanced = 'avancé';

  /// Nouveau
  static const masteryNew = 'Nouveau';

  /// En apprentissage
  static const masteryLearning = 'En apprentissage';

  /// Fragile
  static const masteryFragile = 'Fragile';

  /// Acquis
  static const masteryAcquired = 'Acquis';

  /// Maîtrisé
  static const masteryMastered = 'Maîtrisé';

  /// Connu
  static const masteryKnown = 'Connu';

  /// Statistiques
  static const statsTitle = 'Statistiques';

  /// Tous les exercices
  static const statsAllDrills = 'Tous les exercices';

  /// Aujourd’hui
  static const statsToday = 'Aujourd’hui';

  /// Cartes révisées
  static const statsCardsReviewed = 'Cartes révisées';

  /// Nouvelles cartes
  static const statsNewCards = 'Nouvelles cartes';

  /// Réponses correctes
  static const statsCorrectAnswers = 'Réponses correctes';

  /// Temps passé
  static const statsTimeSpent = 'Temps passé';

  /// Rétention réelle
  static const statsRetention = 'Rétention réelle';

  /// 7 jours
  static const statsLast7Days = '7 jours';

  /// 30 jours
  static const statsLast30Days = '30 jours';

  /// Objectif
  static const statsTargetRetention = 'Objectif';

  /// Niveaux
  static const statsLevels = 'Niveaux';

  /// Prévisions
  static const statsForecast = 'Prévisions';

  /// Cartes à réviser dans les 7 prochains jours
  static const statsForecastHelp =
      'Cartes à réviser dans les 7 prochains jours';

  /// Sessions
  static const statsSessions = 'Sessions';

  /// Mots difficiles
  static const statsHardWords = 'Mots difficiles';

  /// Pas encore de données.
  static const statsNoData = 'Pas encore de données.';

  /// Réglages
  static const settingsTitle = 'Réglages';

  /// Rétention visée
  static const settingsTargetRetention = 'Rétention visée';

  /// Un objectif plus élevé demande plus de révisions, mais on oublie moins.
  static const settingsTargetRetentionHelp =
      'Un objectif plus élevé demande plus de révisions, mais on oublie moins.';

  /// Réglages des exercices
  static const settingsDrillSettings = 'Réglages des exercices';

  /// Mettre à jour le contenu
  static const settingsUpdateContent = 'Mettre à jour le contenu';

  /// Contenu : version {version} · {date}
  static String settingsContentVersion({
    required int version,
    required String date,
  }) => 'Contenu : version $version · $date';

  /// Thème
  static const settingsTheme = 'Thème';

  /// Système
  static const settingsThemeSystem = 'Système';

  /// Clair
  static const settingsThemeLight = 'Clair';

  /// Sombre
  static const settingsThemeDark = 'Sombre';

  /// Rapport de plantage
  static const settingsCrashReports = 'Rapport de plantage';

  /// Envoie des rapports de plantage anonymes. Aucune donnée personnelle, aucune analyse d’usage.
  static const settingsCrashReportsHelp =
      'Envoie des rapports de plantage anonymes. Aucune donnée personnelle, aucune analyse d’usage.';

  /// À propos
  static const settingsAbout = 'À propos';

  /// Réglages – {drill}
  static String drillSettingsTitle({required String drill}) =>
      'Réglages – $drill';

  /// Nouvelles cartes par jour
  static const drillSettingsNewPerDay = 'Nouvelles cartes par jour';

  /// Révisions max par jour
  static const drillSettingsMaxReviewsPerDay = 'Révisions max par jour';

  /// Catégories
  static const drillSettingsCategories = 'Catégories';

  /// Jamais
  static const drillSettingsWeightNever = 'Jamais';

  /// Moins
  static const drillSettingsWeightLess = 'Moins';

  /// Normal
  static const drillSettingsWeightNormal = 'Normal';

  /// Plus
  static const drillSettingsWeightMore = 'Plus';

  /// Afficher l’image
  static const drillSettingsShowImage = 'Afficher l’image';

  /// Article obligatoire
  static const drillSettingsArticleMandatory = 'Article obligatoire';

  /// Il faudra écrire l’article avec le mot.
  static const drillSettingsArticleMandatoryHelp =
      'Il faudra écrire l’article avec le mot.';

  /// Correction en direct
  static const drillSettingsLiveFeedback = 'Correction en direct';

  /// Colore les lettres pendant que vous écrivez.
  static const drillSettingsLiveFeedbackHelp =
      'Colore les lettres pendant que vous écrivez.';

  /// Temps
  static const drillSettingsTenses = 'Temps';

  /// Groupes de verbes
  static const drillSettingsVerbGroups = 'Groupes de verbes';

  /// Les changements s’appliquent à partir de la carte suivante.
  static const drillSettingsAppliesNextCard =
      'Les changements s’appliquent à partir de la carte suivante.';

  /// Mise à jour du contenu
  static const contentUpdateTitle = 'Mise à jour du contenu';

  /// Mettre à jour le contenu
  static const contentUpdateCheck = 'Mettre à jour le contenu';

  /// Vérification…
  static const contentUpdateChecking = 'Vérification…';

  /// Le contenu est à jour
  static const contentUpdateUpToDate = 'Le contenu est à jour';

  /// Version {version} disponible
  static String contentUpdateAvailable({required int version}) =>
      'Version $version disponible';

  /// {size} Mo
  static String contentUpdateSize({required String size}) => '$size Mo';

  /// Télécharger
  static const contentUpdateDownload = 'Télécharger';

  /// Plus tard
  static const contentUpdateLater = 'Plus tard';

  /// Téléchargement…
  static const contentUpdateDownloading = 'Téléchargement…';

  /// Installation…
  static const contentUpdateInstalling = 'Installation…';

  /// Contenu mis à jour : version {version}
  static String contentUpdateDone({required int version}) =>
      'Contenu mis à jour : version $version';

  /// La mise à jour a échoué. Rien n’a été modifié.
  static const contentUpdateFailed =
      'La mise à jour a échoué. Rien n’a été modifié.';

  /// Pas de connexion
  static const contentUpdateNoConnection = 'Pas de connexion';

  /// Mettez à jour l’application pour recevoir ce contenu.
  static const contentUpdateAppTooOld =
      'Mettez à jour l’application pour recevoir ce contenu.';

  /// À propos
  static const aboutTitle = 'À propos';

  /// Version
  static const aboutVersion = 'Version';

  /// Version du contenu
  static const aboutContentVersion = 'Version du contenu';

  /// Licence
  static const aboutLicence = 'Licence';

  /// Code source
  static const aboutSourceCode = 'Code source';

  /// Crédits des images
  static const aboutImageCredits = 'Crédits des images';

  /// Licences des bibliothèques
  static const aboutLibraryLicences = 'Licences des bibliothèques';

  /// Confidentialité
  static const aboutPrivacy = 'Confidentialité';

  /// BAH Français
  static const accessibilityLogo = 'BAH Français';

  /// masculin
  static const accessibilityChooseMasculine = 'masculin';

  /// féminin
  static const accessibilityChooseFeminine = 'féminin';

  /// les deux
  static const accessibilityChooseBoth = 'les deux';

  /// Illustration du mot {word}
  static String accessibilityWordImage({required String word}) =>
      'Illustration du mot $word';

  /// Réponse correcte
  static const accessibilityAnswerCorrect = 'Réponse correcte';

  /// Réponse presque correcte
  static const accessibilityAnswerAlmost = 'Réponse presque correcte';

  /// Réponse incorrecte
  static const accessibilityAnswerIncorrect = 'Réponse incorrecte';

  /// Terminer la session
  static const accessibilityCloseSession = 'Terminer la session';

  /// Lettre accentuée {word}
  static String accessibilityAccentKey({required String word}) =>
      'Lettre accentuée $word';
}

/// The welcome screen's English text, from `strings/strings_en_welcome.json`.
abstract final class WelcomeStrings {
  /// BAH Français
  static const welcomeTitle = 'BAH Français';

  /// Learn and keep your French in the odd spare minute.
  static const welcomeIntro =
      'Learn and keep your French in the odd spare minute.';

  /// Sessions are as short as you like. Start, answer a few cards, stop whenever — nothing is lost.
  static const welcomePointSessions =
      'Sessions are as short as you like. Start, answer a few cards, stop whenever — nothing is lost.';

  /// Words and verbs come back just before you would forget them.
  static const welcomePointSpacedRepetition =
      'Words and verbs come back just before you would forget them.';

  /// No streaks, no badges, no notifications, no accounts.
  static const welcomePointNoPressure =
      'No streaks, no badges, no notifications, no accounts.';

  /// Everything stays on this phone and is included in its backups. Deleting the app deletes your progress.
  static const welcomePointPrivacy =
      'Everything stays on this phone and is included in its backups. Deleting the app deletes your progress.';

  /// Already know a word? Tap “Je le connais” during a drill and it won't come back.
  static const welcomePointKnownWords =
      'Already know a word? Tap “Je le connais” during a drill and it won\'t come back.';

  /// From here on, the app is in French.
  static const welcomePointFrench = 'From here on, the app is in French.';

  /// Send crash reports
  static const welcomeCrashReportsTitle = 'Send crash reports';

  /// Anonymous crash reports only — no personal data and no usage tracking. You can change this any time in Réglages.
  static const welcomeCrashReportsBody =
      'Anonymous crash reports only — no personal data and no usage tracking. You can change this any time in Réglages.';

  /// Preparing content…
  static const welcomePreparingContent = 'Preparing content…';

  /// Commencer
  static const welcomeStart = 'Commencer';
}
